name: Pull Request to develop

on:
  pull_request:
    branches: [develop]

permissions:
  contents: write

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check formatting
        run: poetry run black .

      - name: Push black formatting fixes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.email "action@github.com"
            git config user.name "Lint Action"
            git add -u
            git commit -m "style: apply black formatting [skip ci]"
            git push
          fi

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run unit tests
        run: poetry run pytest mean_field_tools/deep_bsde/test/unit/
